joy_manager:
  topic: /cmd_vel/managed
  type: Twist
  publish_multiple_halt: false
  throttle:
    lin_increment: 0.25
    lin_throttle_ctrl: DPAD_VERT
    ang_increment: 0.25
    ang_throttle_ctrl: DPAD_HORIZ
  turbo: 0
  hip:
  left_reverse: LB
  right_reverse: RB
  data:
    linear:
      x: LEFT_JOY_VERT
      y: LEFT_TRIGGER
      z: RIGHT_TRIGGER
    angular:
      x: 0
      y: RIGHT_JOY_VERT
      z: RIGHT_JOY_HORIZ
